server:
  port: 3001
spring:
  application:
    name: sample-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://rdserver:8769/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: sample-ribbon