server:
  port: 8889

spring:
  application:
    name: sample-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

eureka:
  client:
    serviceUrl:
      defaultZone: http://zkserver:8769/eureka/,http://rdserver:8761/eureka/
